# Generated by Django 4.2.7 on 2023-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesacal', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('registered_users', 'Send Money to Another M-pesa'), ('agent_withdrawal', 'Withdraw from Agent'), ('unregistered_users', 'Send Money to Unregistered User'), ('atm_withdrawal', 'ATM Withdrawal'), ('other_network_users', 'Send Money to Another Network')], max_length=255)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('registered_users', 'Send Money to Another M-pesa'), ('agent_withdrawal', 'Withdraw from Agent'), ('unregistered_users', 'Send Money to Unregistered User'), ('atm_withdrawal', 'ATM Withdrawal'), ('other_network_users', 'Send Money to Another Network')], max_length=255, null=True),
        ),
    ]
